# Generated by Django 5.2 on 2025-04-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_alter_training_coordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='supervisor',
        ),
        migrations.AlterField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
