# Generated by Django 5.2 on 2025-04-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_enrollment_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='concept_note',
            field=models.FileField(blank=True, null=True, upload_to='concept_notes/'),
        ),
    ]
