# Generated by Django 5.2 on 2025-04-15 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_staff_email_staff_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact_number',
            field=models.CharField(blank=True, default='unkown', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('regular', 'Regular'), ('supervisor', 'Supervisor')], max_length=50, null=True),
        ),
    ]
