# Generated by Django 5.2 on 2025-04-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0009_remove_staff_email_alter_staff_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='participant_photos/'),
        ),
    ]
